### ISSUE TITLE
TrueLens on the cluster crashes and don't start leads to memory spike and pod restart

### ISSUE THREAD

**Issue by LatVAlY** [truera/trulens#1260]
**Bug Description**
after adding logs after the TruLens initialization tru = Tru() the trueLens is initialized but it spikes memory to a level where the pod runs out of memory, disabling TrueLens everything works fine (POD).

I have increased memory limit to 2G but that didn't resolve the issue either
**Environment:**
trulens-eval = "^0.31.0"

I don't know what other additional info I should put here to help resolve or debug the issue, but you need more info happy to provide

**Comment by sfc-gh-jreini** [comment]
Hi @LatVAlY - we aimed to address the root of this problem with [TruLens 1.0](https://github.com/truera/trulens/releases/tag/trulens-1.0.1). Was this ever resolved? If not, can you let us know if it still occurs with TruLens 1.0?

**Comment by sfc-gh-jreini** [comment]
@LatVAlY closing this for now. Let us know if this issue persists on <1.0 TruLens vesions.

**Comment by sfc-gh-jreini** [comment]
TruLens 2.8 introduces a batch-oriented Run API that may help with this class of issue. Instead of an always-on evaluator that processes feedback in the background (which contributed to memory pressure), the Run API lets you control exactly when invocations and metrics run:

```python
run = tru_app.run(run_name="my_run")
run.start(input_df)
run.compute_metrics(metrics)
```

No background threads or evaluator processes — everything runs in the foreground with configurable concurrency via `metric_max_workers`.

PR: https://github.com/truera/trulens/pull/2391
