### ISSUE TITLE
[BUG] Total token and total cost not captured for llamaindex with azure openai

### ISSUE THREAD

**Issue by zhongshuai-cao** [truera/trulens#1342]
**Bug Description**
Leaderboard shows 0 total token and 0 total cost, while using Llama_index and Azure OpenAI

**To Reproduce**
When I run the leaderboard after I tested some questions, I realize the total token and total cost not working

**Expected behavior**
leaderboard display the token and cost

**Relevant Logs/Tracebacks**
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If the issue is related to the TruLens dashboard, please also include a screenshot.

**Environment:**

- OS: MacOS
- Python Version: 3.11
- TruLens version: 0.33.0
- llama-index: 0.10.57

**Additional context**
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/ac058293-1410-4825-a78c-0b47965c2b49">

**Comment by zhongshuai-cao** [comment]
@dosu would you provide the example of the implementation used in OpenAI to calculate the cost? I may have different models with different unit cost.

**Comment by sfc-gh-dkurokawa** [comment]
We can't do this automatically it seems, because Azure OpenAI just doesn't seem to report this info back to us. `langchain` has a community way of getting around this by estimating it from the reported tokens (see [here](https://python.langchain.com/v0.2/docs/integrations/chat/azure_chat_openai/#specifying-model-version)) but that has its own issues in that your `langchain-community` package would have to be up-to-date, the actual code of that package would have to be up-to-date, and that you specified the right model version.

All this to say, I generally don't think we should go with that kinda approach, but if there's enough desire for it we could do it I suppose.
